name: lean_extensions
description: A collection of extension methods without flutter dependency
version: 0.8.0
repository: https://github.com/gbassisp/lean_extensions

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  any_date: ^0.1.2
  collection: ^1.0.0
  json_annotation: ^4.0.0
  meta: ^1.0.0

dev_dependencies:
  test: 
  very_good_analysis:
