name: lean_extensions
description: A collection of extension methods without flutter dependency. Also includes some python-like functionality and json converters for easy validation
version: 1.3.0
repository: https://github.com/gbassisp/lean_extensions
homepage: https://github.com/gbassisp/lean_extensions

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  any_date: ">=0.1.0 <2.0.0"
  collection: ^1.0.0
  english_numerals: ^1.0.0
  json_annotation: ^4.1.0
  meta: ^1.9.0

dev_dependencies:
  test: 
  very_good_analysis:
