name: lean_extensions
description: A collection of extension methods without flutter dependency
version: 0.1.1
repository: https://github.com/gbassisp/lean_extensions

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  json_annotation: ^4.0.0

dev_dependencies:
  test: 
  very_good_analysis:
